### ISSUE TITLE
@nativescript/capacitor repository

### ISSUE THREAD

**Issue by jdnichollsc** [NativeScript/capacitor-docs#1]
Hello folks, Is this the correct repository to report issues about @nativescript/capacitor package? The link from npm looks wrong, please let me know and thanks in advance!

![Screenshot_20210318-005306_Chrome.jpg](https://user-images.githubusercontent.com/2154886/111579964-e148a780-8784-11eb-9124-7015797b5fc1.jpg)

**Comment by NathanWalker** [comment]
@jdnichollsc this is it and thank you.
We will be making the /capacitor repo public alongside the nativescript 8 release at end of this month. The docs will always live here though.

**Comment by jdnichollsc** [comment]
Awesome, thanks mate! Also, exist any example to create native classes? e.g: https://github.com/proyecto26/nativescript-inappbrowser/blob/develop/src/InAppBrowser.ios.ts#L36

Thanks for your help! 🖤

**Comment by gustavopch** [comment]
@NathanWalker Is the repository still private? https://github.com/NativeScript/capacitor gives me a 404.

**Comment by NathanWalker** [comment]
@gustavopch we decided to make it public with ngConf at end of this week since myself and Osei are giving a talk about it on Friday.
